"""Create user table

Revision ID: b6f0a9201e1f
Revises: 635ac7a9b59e
Create Date: 2025-11-20 23:00:50.712444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f0a9201e1f'
down_revision: Union[str, None] = '635ac7a9b59e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_time', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('update_time', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_deleted')
    op.drop_column('user', 'update_time')
    op.drop_column('user', 'create_time')
    # ### end Alembic commands ###
