"""project_viewers新增字段

Revision ID: 30c3aaafb8ef
Revises: d8b753fc887f
Create Date: 2025-12-04 10:03:39.276999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c3aaafb8ef'
down_revision: Union[str, None] = 'd8b753fc887f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 添加 create_time 字段，允许为 NULL
    op.add_column('project_viewers', sa.Column('create_time', sa.DateTime(), nullable=True))
    # 2. 添加 update_time 字段，允许为 NULL
    op.add_column('project_viewers', sa.Column('update_time', sa.DateTime(), nullable=True))
    # 3. 添加 is_deleted 字段，允许为 NULL
    op.add_column('project_viewers', sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # 4. 更新现有行，设置合理的默认值
    op.execute("UPDATE project_viewers SET create_time = NOW() WHERE create_time IS NULL")
    op.execute("UPDATE project_viewers SET update_time = NOW() WHERE update_time IS NULL")
    op.execute("UPDATE project_viewers SET is_deleted = FALSE WHERE is_deleted IS NULL")

    # 5. 将列改为 NOT NULL，并指定 existing_type
    op.alter_column('project_viewers', 'create_time',
                    existing_type=sa.DateTime(),
                    nullable=False)

    op.alter_column('project_viewers', 'update_time',
                    existing_type=sa.DateTime(),
                    nullable=False)

    op.alter_column('project_viewers', 'is_deleted',
                    existing_type=sa.Boolean(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_viewers', 'is_deleted')
    op.drop_column('project_viewers', 'update_time')
    op.drop_column('project_viewers', 'create_time')
    # ### end Alembic commands ###
