"""建doc表

Revision ID: 3f52115026e1
Revises: ef4e0f391b34
Create Date: 2025-12-03 09:46:51.279768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3f52115026e1'
down_revision: Union[str, None] = 'ef4e0f391b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True, comment='文档名称'),
    sa.Column('file_uuid', sa.String(length=255), nullable=True, comment='文档唯一标识'),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUEING', 'REVIEWING', 'REVIEWED', 'FAILED', name='docstatus'), nullable=True, comment='文档状态：0-排队中, 1-审核中, 2-审核成功, 3-审核失败'),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_uuid')
    )
    op.create_index(op.f('ix_doc_file_name'), 'doc', ['file_name'], unique=False)
    op.create_index(op.f('ix_doc_id'), 'doc', ['id'], unique=False)
    op.alter_column('project', 'project_type',
               existing_type=mysql.INTEGER(),
               type_=sa.Enum('PRIVATE', 'PUBLIC', name='projecttype'),
               existing_comment='0-私有项目, 1-公开项目',
               existing_nullable=True)
    op.alter_column('project', 'is_deleted',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               comment=None,
               existing_comment='逻辑删除标记')
    op.drop_column('project', 'created_at')
    op.drop_column('project', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('updated_at', mysql.DATETIME(), nullable=False))
    op.add_column('project', sa.Column('created_at', mysql.DATETIME(), nullable=False))
    op.alter_column('project', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               nullable=True,
               comment='逻辑删除标记')
    op.alter_column('project', 'project_type',
               existing_type=sa.Enum('PRIVATE', 'PUBLIC', name='projecttype'),
               type_=mysql.INTEGER(),
               existing_comment='0-私有项目, 1-公开项目',
               existing_nullable=True)
    op.drop_index(op.f('ix_doc_id'), table_name='doc')
    op.drop_index(op.f('ix_doc_file_name'), table_name='doc')
    op.drop_table('doc')
    # ### end Alembic commands ###
