"""project_viewers新增id字段用来作为主键

Revision ID: d7f5794dc00a
Revises: 30c3aaafb8ef
Create Date: 2025-12-04 21:51:35.765672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f5794dc00a'
down_revision: Union[str, None] = '30c3aaafb8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_viewers', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_project_viewers_id'), 'project_viewers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_viewers_id'), table_name='project_viewers')
    op.drop_column('project_viewers', 'id')
    # ### end Alembic commands ###
