"""修改枚举值

Revision ID: d8b753fc887f
Revises: e9ea28fecd9a
Create Date: 2025-12-03 09:58:59.024880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd8b753fc887f'
down_revision: Union[str, None] = 'e9ea28fecd9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'project_type',
               existing_type=mysql.ENUM('PRIVATE', 'PUBLIC', collation='utf8mb4_general_ci'),
               type_=sa.Integer(),
               existing_comment='0-私有项目, 1-公开项目',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'project_type',
               existing_type=sa.Integer(),
               type_=mysql.ENUM('PRIVATE', 'PUBLIC', collation='utf8mb4_general_ci'),
               existing_comment='0-私有项目, 1-公开项目',
               existing_nullable=True)
    # ### end Alembic commands ###
