"""修改枚举值

Revision ID: e9ea28fecd9a
Revises: 3f52115026e1
Create Date: 2025-12-03 09:57:23.838294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e9ea28fecd9a'
down_revision: Union[str, None] = '3f52115026e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doc', 'status',
               existing_type=mysql.ENUM('QUEUEING', 'REVIEWING', 'REVIEWED', 'FAILED', collation='utf8mb4_general_ci'),
               type_=sa.Integer(),
               existing_comment='文档状态：0-排队中, 1-审核中, 2-审核成功, 3-审核失败',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doc', 'status',
               existing_type=sa.Integer(),
               type_=mysql.ENUM('QUEUEING', 'REVIEWING', 'REVIEWED', 'FAILED', collation='utf8mb4_general_ci'),
               existing_comment='文档状态：0-排队中, 1-审核中, 2-审核成功, 3-审核失败',
               existing_nullable=True)
    # ### end Alembic commands ###
